version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: student_user
      MYSQL_PASSWORD: student_user_password
      MYSQL_DATABASE: student

  spring-boot-app:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/student
        SPRING_DATASOURCE_USERNAME: student_user
        SPRING_DATASOURCE_PASSWORD: student_user_password

  react-app:
      build:
        context: ./frontend
        dockerfile: Dockerfile
        
      ports:
        - "5000:4000"